title: Therrance blog
author: Taras
email: lozuvatka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Taras

# social links
twitter_username: ze3a # DO NOT include the @ character, or else the build will fail!
github_username:  therrance # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
